<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\CityIntel;
use App\Models\ElectricalStandard;
use App\Models\EmergencyContact;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class CityIntelSeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            [
                'name' => 'Tokyo',
                'slug' => 'tokyo',
                'country_code' => 'JP',
                'state_region' => 'Kanto',
                'timezone' => 'Asia/Tokyo',
                'currency_code' => 'JPY',
                'primary_language' => 'Japanese',
                'latitude' => 35.6762,
                'longitude' => 139.6503,
                'hero_image_url' => 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#8b5cf6',
                'intel' => [
                    'tagline' => 'Neon towers, shrine alleys, and punctual trains.',
                    'summary' => 'Tokyo blends future-forward districts with quiet shrines. Expect efficiency, endless food options, and reliable transit.',
                    'currency_rate' => 0.0068,
                    'electrical_plugs' => 'Type A/B',
                    'voltage' => '100V · 50/60Hz',
                    'emergency_numbers' => [
                        ['label' => 'Police', 'number' => '110'],
                        ['label' => 'Ambulance / Fire', 'number' => '119'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Shinjuku', 'note' => 'Skyscrapers, nightlife, major transit hub'],
                        ['name' => 'Shibuya', 'note' => 'Youth culture, shopping, famous crossing'],
                        ['name' => 'Asakusa', 'note' => 'Historic temples, market streets'],
                    ],
                    'checklist' => [
                        'Grab a Suica/PASMO IC card for trains and convenience stores.',
                        'Pocket Wi-Fi or eSIM for maps and translations.',
                        'Cash-friendly city: keep small yen bills/coins.',
                        'Learn basic phrases: sumimasen (excuse me), arigato (thank you).',
                    ],
                    'cultural_notes' => [
                        'Stand on the left on escalators (except Osaka).',
                        'Quiet phone calls on trains; keep volume low.',
                        'On-time culture: arrive a few minutes early.',
                    ],
                    'weather' => [
                        'snapshot' => 'Mild spring · 18°C',
                        'seasonality' => 'Hot, humid summers; crisp autumns; chilly winters with occasional snow.',
                    ],
                    'visa' => 'Most travelers get 90 days visa-free; verify by passport.',
                    'best_months' => ['March', 'April', 'October', 'November'],
                    'transport' => [
                        'cheat_sheet' => 'JR + Metro lines cover most areas; taxis are safe but pricey.',
                        'from_airport' => 'Narita Express or Keisei Skyliner; Haneda via Monorail/Keikyu.',
                    ],
                    'budget' => [
                        'low' => '¥8,000–12,000 / day',
                        'mid' => '¥15,000–25,000 / day',
                        'high' => '¥30,000+ / day',
                    ],
                ],
            ],
            [
                'name' => 'London',
                'slug' => 'london',
                'country_code' => 'GB',
                'state_region' => 'Greater London',
                'timezone' => 'Europe/London',
                'currency_code' => 'GBP',
                'primary_language' => 'English',
                'latitude' => 51.5072,
                'longitude' => -0.1276,
                'hero_image_url' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#2563eb',
                'intel' => [
                    'tagline' => 'Royal parks, markets, and theatre after dark.',
                    'summary' => 'A walkable city stitched together by Tube lines and neighborhoods with distinct moods.',
                    'currency_rate' => 1.26,
                    'electrical_plugs' => 'Type G',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '999'],
                        ['label' => 'EU-standard', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Shoreditch', 'note' => 'Creative, nightlife, street art'],
                        ['name' => 'Soho', 'note' => 'Dining, theatre, lively evenings'],
                        ['name' => 'South Bank', 'note' => 'Riverside walks, culture, skyline views'],
                    ],
                    'checklist' => [
                        'Oyster or contactless card for Tube/bus.',
                        'Pack layers and a compact umbrella.',
                        'Book theatre tickets ahead for West End shows.',
                    ],
                    'cultural_notes' => [
                        'Queue etiquette matters; join the line.',
                        'Stand on the right on escalators.',
                        'Tap to pay widely accepted, even on buses.',
                    ],
                    'weather' => [
                        'snapshot' => 'Cool · 12°C with light rain',
                        'seasonality' => 'Mild winters, unpredictable showers year-round.',
                    ],
                    'visa' => 'Check UK entry rules; eGates for many passports.',
                    'best_months' => ['May', 'June', 'September'],
                    'transport' => [
                        'cheat_sheet' => 'Tube for speed; buses for views; walking often fastest in Zone 1.',
                        'from_airport' => 'Heathrow Express/Elizabeth line; Gatwick via Thameslink or Express.',
                    ],
                    'budget' => [
                        'low' => '£70–110 / day',
                        'mid' => '£140–220 / day',
                        'high' => '£250+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Bangkok',
                'slug' => 'bangkok',
                'country_code' => 'TH',
                'state_region' => 'Bangkok',
                'timezone' => 'Asia/Bangkok',
                'currency_code' => 'THB',
                'primary_language' => 'Thai',
                'latitude' => 13.7563,
                'longitude' => 100.5018,
                'hero_image_url' => 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#f97316',
                'intel' => [
                    'tagline' => 'Skytrain views, river temples, night markets.',
                    'summary' => 'Bangkok mixes glittering malls with alleys of street food and canals.',
                    'currency_rate' => 0.027,
                    'electrical_plugs' => 'Type A/B/C',
                    'voltage' => '220V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Tourist Police', 'number' => '1155'],
                        ['label' => 'Emergency', 'number' => '1669'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Ari', 'note' => 'Cafés, leafy streets, boutique hotels'],
                        ['name' => 'Thonglor', 'note' => 'Dining, nightlife, modern malls'],
                        ['name' => 'Rattanakosin', 'note' => 'Grand Palace, classic temples'],
                    ],
                    'checklist' => [
                        'Carry cash for markets; cards accepted in malls.',
                        'Respect temple dress codes (shoulders/knees covered).',
                        'Use BTS/MRT or river boats to dodge traffic.',
                    ],
                    'cultural_notes' => [
                        'Wai greeting is appreciated; remove shoes before entering homes/temples.',
                        'Avoid touching heads; be mindful around images of the King.',
                    ],
                    'weather' => [
                        'snapshot' => 'Humid · 30°C with afternoon storms',
                        'seasonality' => 'Hot year-round; coolest and driest Nov–Feb.',
                    ],
                    'visa' => 'Many nationalities get 30–45 day exemption; confirm before arrival.',
                    'best_months' => ['November', 'December', 'January', 'February'],
                    'transport' => [
                        'cheat_sheet' => 'BTS/MRT for speed; Grab/taxis inexpensive but traffic heavy.',
                        'from_airport' => 'Airport Rail Link to Phaya Thai; taxis use meter.',
                    ],
                    'budget' => [
                        'low' => '฿1,200–1,800 / day',
                        'mid' => '฿2,000–3,500 / day',
                        'high' => '฿4,500+ / day',
                    ],
                ],
            ],
            [
                'name' => 'New York',
                'slug' => 'new-york',
                'country_code' => 'US',
                'state_region' => 'New York',
                'timezone' => 'America/New_York',
                'currency_code' => 'USD',
                'primary_language' => 'English',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'hero_image_url' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#0ea5e9',
                'intel' => [
                    'tagline' => 'Skyline energy, bagels, and late-night subway rides.',
                    'summary' => 'NYC is a patchwork of boroughs with 24/7 transit, bold art, and food from everywhere.',
                    'currency_rate' => 1.00,
                    'electrical_plugs' => 'Type A/B',
                    'voltage' => '120V · 60Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '911'],
                        ['label' => 'Non-emergency', 'number' => '311'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Lower Manhattan', 'note' => 'Walkable, history, riverfront parks'],
                        ['name' => 'Brooklyn Heights', 'note' => 'Brownstones, skyline views, easy subway'],
                        ['name' => 'Long Island City', 'note' => 'Modern hotels, quick Midtown access'],
                    ],
                    'checklist' => [
                        'Contactless cards/phones work on OMNY subway readers.',
                        'Comfortable walking shoes; expect 10k+ steps.',
                        'Book timed tickets for major museums/observatories.',
                    ],
                    'cultural_notes' => [
                        'Keep pace on sidewalks; stand right on escalators.',
                        'Tipping culture: 18–22% at restaurants.',
                    ],
                    'weather' => [
                        'snapshot' => 'Crisp · 15°C and clear',
                        'seasonality' => 'Humid summers, snowy winters, perfect shoulder seasons.',
                    ],
                    'visa' => 'ESTA for many visitors; otherwise B visa check.',
                    'best_months' => ['May', 'June', 'September', 'October'],
                    'transport' => [
                        'cheat_sheet' => 'Subway 24/7; buses good for crosstown; yellow/green cabs plentiful.',
                        'from_airport' => 'AirTrain + subway from JFK; NJ Transit/AirTrain from EWR.',
                    ],
                    'budget' => [
                        'low' => '$110–150 / day',
                        'mid' => '$180–260 / day',
                        'high' => '$300+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Paris',
                'slug' => 'paris',
                'country_code' => 'FR',
                'state_region' => 'Île-de-France',
                'timezone' => 'Europe/Paris',
                'currency_code' => 'EUR',
                'primary_language' => 'French',
                'latitude' => 48.8566,
                'longitude' => 2.3522,
                'hero_image_url' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#e11d48',
                'intel' => [
                    'tagline' => 'Boulevard cafés, museums, and Seine sunsets.',
                    'summary' => 'Compact arrondissements linked by Metro lines and tree-lined promenades.',
                    'currency_rate' => 1.08,
                    'electrical_plugs' => 'Type C/E',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                        ['label' => 'Medical', 'number' => '15'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Le Marais', 'note' => 'Boutiques, galleries, nightlife'],
                        ['name' => 'Saint-Germain', 'note' => 'Cafés, bookstores, river walks'],
                        ['name' => 'Canal Saint-Martin', 'note' => 'Trendy bars, relaxed vibe'],
                    ],
                    'checklist' => [
                        'Buy a Navigo Easy pass or contactless tap for Metro.',
                        'Many restaurants close mid-afternoon; plan meals.',
                        'Book Louvre/Eiffel tickets ahead.',
                    ],
                    'cultural_notes' => [
                        'Bonjour/bonsoir greetings before asking questions.',
                        'Keep voices lower in cafés and trains.',
                    ],
                    'weather' => [
                        'snapshot' => 'Mild · 17°C with sun',
                        'seasonality' => 'Cool winters, warm summers; spring/fall are ideal.',
                    ],
                    'visa' => 'Schengen rules apply; 90 days in 180 for many passports.',
                    'best_months' => ['April', 'May', 'September', 'October'],
                    'transport' => [
                        'cheat_sheet' => 'Metro/RER dense network; Velib bikes for short hops.',
                        'from_airport' => 'RER B from CDG; OrlyVal + RER B from ORY.',
                    ],
                    'budget' => [
                        'low' => '€80–120 / day',
                        'mid' => '€140–210 / day',
                        'high' => '€240+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Lisbon',
                'slug' => 'lisbon',
                'country_code' => 'PT',
                'state_region' => 'Lisboa',
                'timezone' => 'Europe/Lisbon',
                'currency_code' => 'EUR',
                'primary_language' => 'Portuguese',
                'latitude' => 38.7223,
                'longitude' => -9.1393,
                'hero_image_url' => 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#6366f1',
                'intel' => [
                    'tagline' => 'Tile-lined hills, tram bells, and Atlantic light.',
                    'summary' => 'A coastal city with miradouros, pastel de nata, and day trips to Sintra and Cascais.',
                    'currency_rate' => 1.08,
                    'electrical_plugs' => 'Type C/F',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Chiado', 'note' => 'Walkable cafés and shops'],
                        ['name' => 'Principe Real', 'note' => 'Boutiques, gardens, nightlife'],
                        ['name' => 'Alfama', 'note' => 'Fado alleys and viewpoints'],
                    ],
                    'checklist' => [
                        'Grab a Viva Viagem card for metro/tram/ferry.',
                        'Pack comfy shoes for hills and cobblestones.',
                        'Reserve Sintra palaces in advance.',
                    ],
                    'cultural_notes' => [
                        'Coffee is a ritual; order bica for espresso.',
                        'Late dinners are common; many kitchens open after 7:30pm.',
                    ],
                    'weather' => [
                        'snapshot' => 'Sunny · 20°C with ocean breeze',
                        'seasonality' => 'Mild winters, warm dry summers.',
                    ],
                    'visa' => 'Schengen rules apply.',
                    'best_months' => ['April', 'May', 'September', 'October'],
                    'transport' => [
                        'cheat_sheet' => 'Metro + trams inside city; trains to Cascais/Sintra.',
                        'from_airport' => 'Metro or rideshare; 20 minutes off-peak.',
                    ],
                    'budget' => [
                        'low' => '€70–100 / day',
                        'mid' => '€110–170 / day',
                        'high' => '€200+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Barcelona',
                'slug' => 'barcelona',
                'country_code' => 'ES',
                'state_region' => 'Catalonia',
                'timezone' => 'Europe/Madrid',
                'currency_code' => 'EUR',
                'primary_language' => 'Catalan/Spanish',
                'latitude' => 41.3874,
                'longitude' => 2.1686,
                'hero_image_url' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#f97316',
                'intel' => [
                    'tagline' => 'Gaudí curves, tapas lanes, beach sunsets.',
                    'summary' => 'Seaside city with Modernisme landmarks, markets, and Mediterranean pace.',
                    'currency_rate' => 1.08,
                    'electrical_plugs' => 'Type C/F',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Eixample', 'note' => 'Grided blocks, cafés, Gaudí homes'],
                        ['name' => 'Gràcia', 'note' => 'Village vibe, plazas, indie shops'],
                        ['name' => 'Barceloneta', 'note' => 'Beachfront boardwalks'],
                    ],
                    'checklist' => [
                        'Pre-book Sagrada Família and Park Güell slots.',
                        'Use T-casual card for metro/bus.',
                        'Mind pickpockets in crowded Ramblas/metro.',
                    ],
                    'cultural_notes' => [
                        'Lunch runs late; dinner often after 9pm.',
                        'Tapas sharing is common; order rounds.',
                    ],
                    'weather' => [
                        'snapshot' => 'Warm · 24°C and breezy',
                        'seasonality' => 'Hot summers, mild winters, shoulder seasons shine.',
                    ],
                    'visa' => 'Schengen rules apply.',
                    'best_months' => ['May', 'June', 'September'],
                    'transport' => [
                        'cheat_sheet' => 'Dense metro network; walking works in center.',
                        'from_airport' => 'Aerobus or R2 Nord train to city.',
                    ],
                    'budget' => [
                        'low' => '€75–110 / day',
                        'mid' => '€130–190 / day',
                        'high' => '€220+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Rome',
                'slug' => 'rome',
                'country_code' => 'IT',
                'state_region' => 'Lazio',
                'timezone' => 'Europe/Rome',
                'currency_code' => 'EUR',
                'primary_language' => 'Italian',
                'latitude' => 41.9028,
                'longitude' => 12.4964,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#eab308',
                'intel' => [
                    'tagline' => 'Fountains, forums, espresso al banco.',
                    'summary' => 'Ancient ruins beside lively trattorias and twilight passeggiata walks.',
                    'currency_rate' => 1.08,
                    'electrical_plugs' => 'Type C/F/L',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Trastevere', 'note' => 'Cobblestones, aperitivo, nightlife'],
                        ['name' => 'Monti', 'note' => 'Boutiques, cafés near the Colosseum'],
                        ['name' => 'Prati', 'note' => 'Calmer, near Vatican, wide avenues'],
                    ],
                    'checklist' => [
                        'Reserve Colosseum/Forum/Vatican tickets in advance.',
                        'Carry small coins for bus/coffee bars.',
                        'Dress code for Vatican sites: cover shoulders/knees.',
                    ],
                    'cultural_notes' => [
                        'Pay at the register after espresso al banco.',
                        'Dinner often starts after 8pm.',
                    ],
                    'weather' => [
                        'snapshot' => 'Warm · 23°C and sunny',
                        'seasonality' => 'Hot summers; best spring/fall.',
                    ],
                    'visa' => 'Schengen rules apply.',
                    'best_months' => ['April', 'May', 'September', 'October'],
                    'transport' => [
                        'cheat_sheet' => 'Metro lines are limited; buses/trams fill gaps.',
                        'from_airport' => 'Leonardo Express to Termini; taxis have fixed city rate.',
                    ],
                    'budget' => [
                        'low' => '€75–110 / day',
                        'mid' => '€130–200 / day',
                        'high' => '€220+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Berlin',
                'slug' => 'berlin',
                'country_code' => 'DE',
                'state_region' => 'Berlin',
                'timezone' => 'Europe/Berlin',
                'currency_code' => 'EUR',
                'primary_language' => 'German',
                'latitude' => 52.52,
                'longitude' => 13.405,
                'hero_image_url' => 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#0ea5e9',
                'intel' => [
                    'tagline' => 'Clubs till sunrise, lakes by noon.',
                    'summary' => 'Creative capital with museums, techno, and expansive green space.',
                    'currency_rate' => 1.08,
                    'electrical_plugs' => 'Type C/F',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Prenzlauer Berg', 'note' => 'Cafés, leafy streets'],
                        ['name' => 'Kreuzberg', 'note' => 'Street food, bars, canal walks'],
                        ['name' => 'Mitte', 'note' => 'Central sights, galleries'],
                    ],
                    'checklist' => [
                        'Buy a transit day ticket; validate once.',
                        'Cash/card mix: many places take cards now.',
                        'Pack layers; weather swings.',
                    ],
                    'cultural_notes' => [
                        'Quiet on Sundays; many shops closed.',
                        'Punctuality appreciated for meetups.',
                    ],
                    'weather' => [
                        'snapshot' => 'Cool · 14°C with clouds',
                        'seasonality' => 'Cold winters, mild summers.',
                    ],
                    'visa' => 'Schengen rules apply.',
                    'best_months' => ['May', 'June', 'September'],
                    'transport' => [
                        'cheat_sheet' => 'U/S-Bahn dense network; bikes popular.',
                        'from_airport' => 'Airport Express to Hauptbahnhof; S-Bahn lines too.',
                    ],
                    'budget' => [
                        'low' => '€70–100 / day',
                        'mid' => '€120–180 / day',
                        'high' => '€210+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Amsterdam',
                'slug' => 'amsterdam',
                'country_code' => 'NL',
                'state_region' => 'Noord-Holland',
                'timezone' => 'Europe/Amsterdam',
                'currency_code' => 'EUR',
                'primary_language' => 'Dutch',
                'latitude' => 52.3676,
                'longitude' => 4.9041,
                'hero_image_url' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#22c55e',
                'intel' => [
                    'tagline' => 'Canals, bikes, museums on every corner.',
                    'summary' => 'Compact, bike-first city with world-class art and cozy brown cafés.',
                    'currency_rate' => 1.08,
                    'electrical_plugs' => 'Type C/F',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Jordaan', 'note' => 'Boutiques, canals, cafés'],
                        ['name' => 'De Pijp', 'note' => 'Food market, lively streets'],
                        ['name' => 'Oost', 'note' => 'Parks, newer restaurants'],
                    ],
                    'checklist' => [
                        'Reserve Anne Frank House tickets far ahead.',
                        'Buy OV-chipkaart for trams/metro.',
                        'Mind bike lanes; look both ways.',
                    ],
                    'cultural_notes' => [
                        'Direct communication is normal.',
                        'Tap water is excellent; refill bottles.',
                    ],
                    'weather' => [
                        'snapshot' => 'Breezy · 16°C and partly cloudy',
                        'seasonality' => 'Frequent rain; mild temps.',
                    ],
                    'visa' => 'Schengen rules apply.',
                    'best_months' => ['May', 'June', 'September'],
                    'transport' => [
                        'cheat_sheet' => 'Trams + bikes; walking covers the center.',
                        'from_airport' => 'Direct train from Schiphol to Centraal.',
                    ],
                    'budget' => [
                        'low' => '€80–110 / day',
                        'mid' => '€130–190 / day',
                        'high' => '€220+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Dubai',
                'slug' => 'dubai',
                'country_code' => 'AE',
                'state_region' => 'Dubai',
                'timezone' => 'Asia/Dubai',
                'currency_code' => 'AED',
                'primary_language' => 'Arabic',
                'latitude' => 25.2048,
                'longitude' => 55.2708,
                'hero_image_url' => 'https://images.unsplash.com/photo-1504274066651-8d31a536b11a?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#0ea5e9',
                'intel' => [
                    'tagline' => 'Skyline desert city with malls and old creek souks.',
                    'summary' => 'Modern architecture meets traditional abra boats, dune drives, and global dining.',
                    'currency_rate' => 0.27,
                    'electrical_plugs' => 'Type G',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Police', 'number' => '999'],
                        ['label' => 'Ambulance', 'number' => '998'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Dubai Marina', 'note' => 'Skyscrapers, beach clubs, restaurants'],
                        ['name' => 'Downtown', 'note' => 'Burj Khalifa, Dubai Mall, fountains'],
                        ['name' => 'Old Dubai', 'note' => 'Creek, gold/spice souks'],
                    ],
                    'checklist' => [
                        'Respect dress codes in malls/old districts.',
                        'Book Burj Khalifa observation slots online.',
                        'Hydrate—heat and AC swings.',
                    ],
                    'cultural_notes' => [
                        'Public displays of affection are limited.',
                        'Friday/Saturday weekend; prayer times matter.',
                    ],
                    'weather' => [
                        'snapshot' => 'Hot · 34°C and dry',
                        'seasonality' => 'Extremely hot summers; best Nov–Mar.',
                    ],
                    'visa' => 'Many nationalities get visa on arrival; confirm requirements.',
                    'best_months' => ['November', 'December', 'January', 'February'],
                    'transport' => [
                        'cheat_sheet' => 'Metro along main corridor; taxis plentiful.',
                        'from_airport' => 'Metro Red Line or taxi; 20–30 minutes to Downtown.',
                    ],
                    'budget' => [
                        'low' => 'AED 250–350 / day',
                        'mid' => 'AED 400–650 / day',
                        'high' => 'AED 800+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Singapore',
                'slug' => 'singapore',
                'country_code' => 'SG',
                'state_region' => 'Singapore',
                'timezone' => 'Asia/Singapore',
                'currency_code' => 'SGD',
                'primary_language' => 'English/Malay',
                'latitude' => 1.3521,
                'longitude' => 103.8198,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#22c55e',
                'intel' => [
                    'tagline' => 'Garden city with hawker feasts and skyline gardens.',
                    'summary' => 'Ultra-efficient, green, and walkable with top-tier food halls.',
                    'currency_rate' => 0.73,
                    'electrical_plugs' => 'Type G',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Police', 'number' => '999'],
                        ['label' => 'Ambulance/Fire', 'number' => '995'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Tiong Bahru', 'note' => 'Art deco blocks, cafés, market'],
                        ['name' => 'Kampong Glam', 'note' => 'Heritage streets, textiles, food'],
                        ['name' => 'Tanjong Pagar', 'note' => 'CBD meets dining and bars'],
                    ],
                    'checklist' => [
                        'Load an EZ-Link card for MRT/bus.',
                        'Pack light clothes; humidity is constant.',
                        'Try hawker staples: chicken rice, laksa, satay.',
                    ],
                    'cultural_notes' => [
                        'Keep areas clean; strict on littering.',
                        'Queue etiquette is observed.',
                    ],
                    'weather' => [
                        'snapshot' => 'Humid · 31°C with possible showers',
                        'seasonality' => 'Equatorial; rain common, temps stable.',
                    ],
                    'visa' => 'Visa-free for many; check ICA site.',
                    'best_months' => ['February', 'March', 'July', 'August'],
                    'transport' => [
                        'cheat_sheet' => 'MRT covers key areas; taxis/ride-hailing plentiful.',
                        'from_airport' => 'MRT from Changi; taxis 20–30 minutes.',
                    ],
                    'budget' => [
                        'low' => 'SGD 80–130 / day',
                        'mid' => 'SGD 150–250 / day',
                        'high' => 'SGD 300+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Sydney',
                'slug' => 'sydney',
                'country_code' => 'AU',
                'state_region' => 'New South Wales',
                'timezone' => 'Australia/Sydney',
                'currency_code' => 'AUD',
                'primary_language' => 'English',
                'latitude' => -33.8688,
                'longitude' => 151.2093,
                'hero_image_url' => 'https://images.unsplash.com/photo-1506976785307-8732e854ad89?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#0ea5e9',
                'intel' => [
                    'tagline' => 'Harbour sails, coastal walks, café culture.',
                    'summary' => 'Beach-to-city days with ferries, markets, and big blue skies.',
                    'currency_rate' => 0.65,
                    'electrical_plugs' => 'Type I',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '000'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Surry Hills', 'note' => 'Cafés, dining, galleries'],
                        ['name' => 'Manly', 'note' => 'Beach vibes via ferry'],
                        ['name' => 'Newtown', 'note' => 'Creative, vintage, food mix'],
                    ],
                    'checklist' => [
                        'Opal card for ferries, trains, buses.',
                        'Sun protection: hat, SPF, sunglasses.',
                        'Book BridgeClimb or Opera House tours early.',
                    ],
                    'cultural_notes' => [
                        'Tap to pay is universal.',
                        'Casual dress norms; beach etiquette matters.',
                    ],
                    'weather' => [
                        'snapshot' => 'Sunny · 22°C coastal breeze',
                        'seasonality' => 'Warm summers; mild winters.',
                    ],
                    'visa' => 'Most need eVisitor or ETA; apply online.',
                    'best_months' => ['October', 'November', 'March', 'April'],
                    'transport' => [
                        'cheat_sheet' => 'Ferries + trains link key spots; walking central core is easy.',
                        'from_airport' => 'Airport train to Central; taxis/ride-share available.',
                    ],
                    'budget' => [
                        'low' => 'AUD 120–180 / day',
                        'mid' => 'AUD 190–280 / day',
                        'high' => 'AUD 320+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Cape Town',
                'slug' => 'cape-town',
                'country_code' => 'ZA',
                'state_region' => 'Western Cape',
                'timezone' => 'Africa/Johannesburg',
                'currency_code' => 'ZAR',
                'primary_language' => 'English',
                'latitude' => -33.9249,
                'longitude' => 18.4241,
                'hero_image_url' => 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#22c55e',
                'intel' => [
                    'tagline' => 'Table Mountain backdrops and wine country escapes.',
                    'summary' => 'Nature-forward city with beaches, hikes, and vibrant food/wine.',
                    'currency_rate' => 0.053,
                    'electrical_plugs' => 'Type D/M/N',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                        ['label' => 'Police', 'number' => '10111'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Gardens/Tamboerskloof', 'note' => 'Close to mountain, cafés'],
                        ['name' => 'Sea Point', 'note' => 'Promenade, ocean views'],
                        ['name' => 'Green Point', 'note' => 'Parks, stadium, walkable'],
                    ],
                    'checklist' => [
                        'Load a local SIM for maps/safety.',
                        'Sunscreen and windbreaker for changing weather.',
                        'Book Table Mountain cable car on clear days.',
                    ],
                    'cultural_notes' => [
                        'Tipping ~10–15% common.',
                        'Be mindful of petty crime; use rideshares at night.',
                    ],
                    'weather' => [
                        'snapshot' => 'Breezy · 19°C',
                        'seasonality' => 'Warm, dry summers; cooler, wet winters.',
                    ],
                    'visa' => 'Many get 90 days visa-free; verify per passport.',
                    'best_months' => ['November', 'December', 'January', 'February'],
                    'transport' => [
                        'cheat_sheet' => 'Rideshare/taxis common; MyCiTi for some routes.',
                        'from_airport' => 'Taxi/rideshare ~25 minutes; airport bus to Civic Centre.',
                    ],
                    'budget' => [
                        'low' => 'R900–1,400 / day',
                        'mid' => 'R1,500–2,500 / day',
                        'high' => 'R3,000+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Mexico City',
                'slug' => 'mexico-city',
                'country_code' => 'MX',
                'state_region' => 'CDMX',
                'timezone' => 'America/Mexico_City',
                'currency_code' => 'MXN',
                'primary_language' => 'Spanish',
                'latitude' => 19.4326,
                'longitude' => -99.1332,
                'hero_image_url' => 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#f97316',
                'intel' => [
                    'tagline' => 'Museums, mezcal bars, and tree-lined colonias.',
                    'summary' => 'High-altitude capital with vibrant food, art, and day trips to Teotihuacan.',
                    'currency_rate' => 0.058,
                    'electrical_plugs' => 'Type A/B',
                    'voltage' => '127V · 60Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '911'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Roma Norte', 'note' => 'Cafés, galleries, leafy streets'],
                        ['name' => 'Condesa', 'note' => 'Parks, restaurants, bike lanes'],
                        ['name' => 'Polanco', 'note' => 'Museums, upscale dining'],
                    ],
                    'checklist' => [
                        'Use bottled water; avoid tap.',
                        'Carry cash for markets; cards in restaurants.',
                        'Altitude ~2,200m—hydrate and pace yourself.',
                    ],
                    'cultural_notes' => [
                        'Lunch can be late; dinner starts after 8pm.',
                        'Tipping 10–15% common.',
                    ],
                    'weather' => [
                        'snapshot' => 'Mild · 22°C with afternoon showers',
                        'seasonality' => 'Dry Nov–Apr; wet afternoons May–Oct.',
                    ],
                    'visa' => 'Many nationalities visa-free; check FMM rules.',
                    'best_months' => ['February', 'March', 'November'],
                    'transport' => [
                        'cheat_sheet' => 'Metro is extensive; rideshare common.',
                        'from_airport' => 'Authorized taxis or rideshare; Metrobus Line 4 to center.',
                    ],
                    'budget' => [
                        'low' => '$900–1,400 MXN / day',
                        'mid' => '$1,600–2,600 MXN / day',
                        'high' => '$3,200+ MXN / day',
                    ],
                ],
            ],
            [
                'name' => 'Vancouver',
                'slug' => 'vancouver',
                'country_code' => 'CA',
                'state_region' => 'British Columbia',
                'timezone' => 'America/Vancouver',
                'currency_code' => 'CAD',
                'primary_language' => 'English',
                'latitude' => 49.2827,
                'longitude' => -123.1207,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#22c55e',
                'intel' => [
                    'tagline' => 'Seawall runs, mountain views, Pacific sushi.',
                    'summary' => 'Waterfront city framed by forests and peaks; outdoor culture year-round.',
                    'currency_rate' => 0.73,
                    'electrical_plugs' => 'Type A/B',
                    'voltage' => '120V · 60Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '911'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Yaletown', 'note' => 'Restaurants, seawall access'],
                        ['name' => 'Kitsilano', 'note' => 'Beaches, cafés'],
                        ['name' => 'Mount Pleasant', 'note' => 'Breweries, murals'],
                    ],
                    'checklist' => [
                        'Compass Card for transit.',
                        'Rain shell for quick showers.',
                        'Book Grouse/Capilano tickets ahead in peak months.',
                    ],
                    'cultural_notes' => [
                        'Tap to pay accepted widely.',
                        'Tipping 15–20% standard.',
                    ],
                    'weather' => [
                        'snapshot' => 'Drizzly · 12°C',
                        'seasonality' => 'Wet winters, mild summers.',
                    ],
                    'visa' => 'Many need eTA; US citizens exempt for short visits.',
                    'best_months' => ['June', 'July', 'August', 'September'],
                    'transport' => [
                        'cheat_sheet' => 'SkyTrain + buses cover most areas; walking downtown is easy.',
                        'from_airport' => 'Canada Line to downtown in ~25 minutes.',
                    ],
                    'budget' => [
                        'low' => '$110–160 CAD / day',
                        'mid' => '$170–260 CAD / day',
                        'high' => '$300+ CAD / day',
                    ],
                ],
            ],
            [
                'name' => 'Reykjavik',
                'slug' => 'reykjavik',
                'country_code' => 'IS',
                'state_region' => 'Capital Region',
                'timezone' => 'Atlantic/Reykjavik',
                'currency_code' => 'ISK',
                'primary_language' => 'Icelandic',
                'latitude' => 64.1466,
                'longitude' => -21.9426,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#6366f1',
                'intel' => [
                    'tagline' => 'Nordic light, geothermal pools, aurora hunts.',
                    'summary' => 'Compact capital, launchpad for waterfalls, glaciers, and lava fields.',
                    'currency_rate' => 0.0073,
                    'electrical_plugs' => 'Type C/F',
                    'voltage' => '230V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '112'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Miðborg', 'note' => 'Harpa, cafés, shops'],
                        ['name' => 'Vesturbær', 'note' => 'Residential, near pools'],
                    ],
                    'checklist' => [
                        'Layered clothing; weather swings fast.',
                        'Book Blue Lagoon/Sky Lagoon slots ahead.',
                        'Rent car or book tours for Golden Circle/South Coast.',
                    ],
                    'cultural_notes' => [
                        'Tipping not expected; round up if you wish.',
                        'Pools have strict shower etiquette.',
                    ],
                    'weather' => [
                        'snapshot' => 'Chilly · 6°C windy',
                        'seasonality' => 'Cool summers, cold winters; long daylight in summer.',
                    ],
                    'visa' => 'Schengen rules apply.',
                    'best_months' => ['June', 'July', 'August for light', 'February', 'March for aurora'],
                    'transport' => [
                        'cheat_sheet' => 'Walkable center; buses reliable; car best for excursions.',
                        'from_airport' => 'Flybus/Gray Line shuttles or rental car from KEF (~45 min).',
                    ],
                    'budget' => [
                        'low' => 'kr 18,000–24,000 / day',
                        'mid' => 'kr 26,000–38,000 / day',
                        'high' => 'kr 45,000+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Marrakech',
                'slug' => 'marrakech',
                'country_code' => 'MA',
                'state_region' => 'Marrakech-Safi',
                'timezone' => 'Africa/Casablanca',
                'currency_code' => 'MAD',
                'primary_language' => 'Arabic',
                'latitude' => 31.6295,
                'longitude' => -7.9811,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#f97316',
                'intel' => [
                    'tagline' => 'Rose-hued medina, riads, desert day trips.',
                    'summary' => 'Labyrinthine souks, rooftop sunsets, and Atlas Mountain escapes.',
                    'currency_rate' => 0.10,
                    'electrical_plugs' => 'Type C/E',
                    'voltage' => '220V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Police', 'number' => '190'],
                        ['label' => 'Ambulance/Fire', 'number' => '150'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Medina', 'note' => 'Riads, souks, historic sites'],
                        ['name' => 'Gueliz', 'note' => 'Modern cafés, galleries'],
                        ['name' => 'Palmeraie', 'note' => 'Resorts, palms, calm'],
                    ],
                    'checklist' => [
                        'Carry small bills/coins for bargaining.',
                        'Dress modestly in the medina.',
                        'Arrange riad airport pickup if arriving late.',
                    ],
                    'cultural_notes' => [
                        'Haggling expected in markets.',
                        'Friday prayers may affect hours.',
                    ],
                    'weather' => [
                        'snapshot' => 'Warm · 27°C and dry',
                        'seasonality' => 'Hot summers; pleasant spring/fall.',
                    ],
                    'visa' => '90 days visa-free for many; confirm.',
                    'best_months' => ['March', 'April', 'October', 'November'],
                    'transport' => [
                        'cheat_sheet' => 'Taxis common; walk medina; arrange drivers for Atlas/Agafay.',
                        'from_airport' => 'Taxi or riad transfer; fixed rates posted.',
                    ],
                    'budget' => [
                        'low' => 'MAD 500–800 / day',
                        'mid' => 'MAD 900–1,400 / day',
                        'high' => 'MAD 1,800+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Buenos Aires',
                'slug' => 'buenos-aires',
                'country_code' => 'AR',
                'state_region' => 'Buenos Aires',
                'timezone' => 'America/Argentina/Buenos_Aires',
                'currency_code' => 'ARS',
                'primary_language' => 'Spanish',
                'latitude' => -34.6037,
                'longitude' => -58.3816,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#0ea5e9',
                'intel' => [
                    'tagline' => 'Tango nights, parrillas, leafy avenidas.',
                    'summary' => 'European-influenced boulevards mixed with vibrant street art and late-night culture.',
                    'currency_rate' => 0.0011,
                    'electrical_plugs' => 'Type C/I',
                    'voltage' => '220V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '911'],
                        ['label' => 'Medical', 'number' => '107'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Palermo', 'note' => 'Parks, cafés, bars'],
                        ['name' => 'Recoleta', 'note' => 'Architecture, museums'],
                        ['name' => 'San Telmo', 'note' => 'Antiques, tango, markets'],
                    ],
                    'checklist' => [
                        'Carry cash; card acceptance varies.',
                        'Plan for late dining; reservations recommended weekends.',
                        'Use trusted taxis or rideshare at night.',
                    ],
                    'cultural_notes' => [
                        'Kiss on the cheek as greeting is common.',
                        'Meals are social and unhurried.',
                    ],
                    'weather' => [
                        'snapshot' => 'Mild · 19°C and clear',
                        'seasonality' => 'Hot summers; mild winters; spring/fall best.',
                    ],
                    'visa' => 'Many get 90 days visa-free; confirm rules.',
                    'best_months' => ['September', 'October', 'March', 'April'],
                    'transport' => [
                        'cheat_sheet' => 'Subte + buses with SUBE card; rideshare abundant.',
                        'from_airport' => 'EZE: remis/rideshare; AEP close to center.',
                    ],
                    'budget' => [
                        'low' => 'ARS 22,000–35,000 / day',
                        'mid' => 'ARS 40,000–65,000 / day',
                        'high' => 'ARS 80,000+ / day',
                    ],
                ],
            ],
            [
                'name' => 'Nairobi',
                'slug' => 'nairobi',
                'country_code' => 'KE',
                'state_region' => 'Nairobi',
                'timezone' => 'Africa/Nairobi',
                'currency_code' => 'KES',
                'primary_language' => 'English/Swahili',
                'latitude' => -1.2921,
                'longitude' => 36.8219,
                'hero_image_url' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
                'accent_color' => '#22c55e',
                'intel' => [
                    'tagline' => 'Savanna gateway with tech hubs and coffee culture.',
                    'summary' => 'Urban energy near wildlife parks; thriving art, music, and food scenes.',
                    'currency_rate' => 0.007,
                    'electrical_plugs' => 'Type G',
                    'voltage' => '240V · 50Hz',
                    'emergency_numbers' => [
                        ['label' => 'Emergency', 'number' => '999'],
                        ['label' => 'Ambulance', 'number' => '1199'],
                    ],
                    'neighborhoods' => [
                        ['name' => 'Kilimani', 'note' => 'Cafés, restaurants, central'],
                        ['name' => 'Westlands', 'note' => 'Nightlife, malls'],
                        ['name' => 'Karen', 'note' => 'Leafy, close to Nairobi National Park/Giraffe Centre'],
                    ],
                    'checklist' => [
                        'Arrange airport pickup for late arrivals.',
                        'Use trusted taxis/rideshare; avoid walking late.',
                        'Yellow fever proof may be asked when arriving from some countries.',
                    ],
                    'cultural_notes' => [
                        'Greetings matter; start conversations politely.',
                        'Tipping 5–10% appreciated.',
                    ],
                    'weather' => [
                        'snapshot' => 'Mild · 21°C',
                        'seasonality' => 'Warm days, cool nights; rains in Mar–May and Oct–Nov.',
                    ],
                    'visa' => 'eVisa/ETA required for most; check latest rules.',
                    'best_months' => ['July', 'August', 'January', 'February'],
                    'transport' => [
                        'cheat_sheet' => 'Rideshare/taxis preferred; BRT expanding.',
                        'from_airport' => 'JKIA to city via taxi or expressway (~25–40 min).',
                    ],
                    'budget' => [
                        'low' => 'KES 7,000–11,000 / day',
                        'mid' => 'KES 12,000–20,000 / day',
                        'high' => 'KES 24,000+ / day',
                    ],
                ],
            ],
        ];

        foreach ($cities as $payload) {
            // Keep media local/offline
            $payload['hero_image_url'] = 'placeholders/city.jpg';
            $city = City::updateOrCreate(
                ['slug' => $payload['slug'] ?? Str::slug($payload['name'].'-'.$payload['country_code'])],
                Arr::only($payload, [
                    'name',
                    'country_code',
                    'state_region',
                    'timezone',
                    'currency_code',
                    'primary_language',
                    'latitude',
                    'longitude',
                    'hero_image_url',
                    'accent_color',
                    'slug',
                ])
            );

            $intel = $payload['intel'] ?? [];

            CityIntel::updateOrCreate(
                ['city_id' => $city->id],
                [
                    'city_id' => $city->id,
                    'tagline' => $intel['tagline'] ?? null,
                    'summary' => $intel['summary'] ?? null,
                    'local_time_label' => $payload['timezone'] ?? null,
                    'currency_code' => $payload['currency_code'] ?? null,
                    'currency_rate' => $intel['currency_rate'] ?? null,
                    'electrical_plugs' => $intel['electrical_plugs'] ?? null,
                    'voltage' => $intel['voltage'] ?? null,
                    'emergency_numbers' => $intel['emergency_numbers'] ?? [],
                    'neighborhoods' => $intel['neighborhoods'] ?? [],
                    'checklist' => $intel['checklist'] ?? [],
                    'cultural_notes' => $intel['cultural_notes'] ?? [],
                    'weather' => $intel['weather'] ?? [],
                    'visa' => $intel['visa'] ?? null,
                    'best_months' => $intel['best_months'] ?? [],
                    'transport' => $intel['transport'] ?? [],
                    'budget' => $intel['budget'] ?? [],
                ]
            );
        }

        $electricalStandards = [
            'JP' => ['plug_types' => 'A/B', 'voltage' => '100V', 'frequency' => '50/60Hz'],
            'GB' => ['plug_types' => 'G', 'voltage' => '230V', 'frequency' => '50Hz'],
            'TH' => ['plug_types' => 'A/B/C', 'voltage' => '220V', 'frequency' => '50Hz'],
            'US' => ['plug_types' => 'A/B', 'voltage' => '120V', 'frequency' => '60Hz'],
            'FR' => ['plug_types' => 'C/E', 'voltage' => '230V', 'frequency' => '50Hz'],
            'PT' => ['plug_types' => 'C/F', 'voltage' => '230V', 'frequency' => '50Hz'],
            'ES' => ['plug_types' => 'C/F', 'voltage' => '230V', 'frequency' => '50Hz'],
            'IT' => ['plug_types' => 'C/F/L', 'voltage' => '230V', 'frequency' => '50Hz'],
            'DE' => ['plug_types' => 'C/F', 'voltage' => '230V', 'frequency' => '50Hz'],
            'NL' => ['plug_types' => 'C/F', 'voltage' => '230V', 'frequency' => '50Hz'],
            'AE' => ['plug_types' => 'G', 'voltage' => '230V', 'frequency' => '50Hz'],
            'SG' => ['plug_types' => 'G', 'voltage' => '230V', 'frequency' => '50Hz'],
            'AU' => ['plug_types' => 'I', 'voltage' => '230V', 'frequency' => '50Hz'],
            'ZA' => ['plug_types' => 'D/M/N', 'voltage' => '230V', 'frequency' => '50Hz'],
            'MX' => ['plug_types' => 'A/B', 'voltage' => '127V', 'frequency' => '60Hz'],
            'CA' => ['plug_types' => 'A/B', 'voltage' => '120V', 'frequency' => '60Hz'],
            'IS' => ['plug_types' => 'C/F', 'voltage' => '230V', 'frequency' => '50Hz'],
            'MA' => ['plug_types' => 'C/E', 'voltage' => '220V', 'frequency' => '50Hz'],
            'AR' => ['plug_types' => 'C/I', 'voltage' => '220V', 'frequency' => '50Hz'],
            'KE' => ['plug_types' => 'G', 'voltage' => '240V', 'frequency' => '50Hz'],
        ];

        foreach ($electricalStandards as $country => $values) {
            ElectricalStandard::updateOrCreate(
                ['country_code' => $country],
                [
                    ...$values,
                    'notes' => ['source' => 'seeded placeholder'],
                ]
            );
        }

        $emergencyContacts = [
            ['country_code' => 'JP', 'service' => 'Police', 'number' => '110', 'note' => 'Nationwide'],
            ['country_code' => 'JP', 'service' => 'Ambulance/Fire', 'number' => '119', 'note' => 'Nationwide'],
            ['country_code' => 'GB', 'service' => 'Emergency', 'number' => '999', 'note' => 'UK emergency'],
            ['country_code' => 'GB', 'service' => 'EU Standard', 'number' => '112', 'note' => 'Works across EU'],
            ['country_code' => 'TH', 'service' => 'Tourist Police', 'number' => '1155', 'note' => 'English support'],
            ['country_code' => 'TH', 'service' => 'Medical Emergency', 'number' => '1669', 'note' => 'Bangkok'],
            ['country_code' => 'US', 'service' => 'Emergency', 'number' => '911', 'note' => 'Nationwide'],
            ['country_code' => 'US', 'service' => 'Info', 'number' => '311', 'note' => 'NYC services'],
            ['country_code' => 'FR', 'service' => 'Emergency', 'number' => '112', 'note' => 'EU standard'],
            ['country_code' => 'FR', 'service' => 'Medical', 'number' => '15', 'note' => 'SAMU'],
            ['country_code' => 'PT', 'service' => 'Emergency', 'number' => '112', 'note' => 'Portugal'],
            ['country_code' => 'ES', 'service' => 'Emergency', 'number' => '112', 'note' => 'Spain/EU'],
            ['country_code' => 'IT', 'service' => 'Emergency', 'number' => '112', 'note' => 'Italy/EU'],
            ['country_code' => 'DE', 'service' => 'Emergency', 'number' => '112', 'note' => 'Germany/EU'],
            ['country_code' => 'NL', 'service' => 'Emergency', 'number' => '112', 'note' => 'Netherlands/EU'],
            ['country_code' => 'AE', 'service' => 'Police', 'number' => '999', 'note' => 'UAE'],
            ['country_code' => 'AE', 'service' => 'Ambulance', 'number' => '998', 'note' => 'UAE'],
            ['country_code' => 'SG', 'service' => 'Police', 'number' => '999', 'note' => 'Singapore'],
            ['country_code' => 'SG', 'service' => 'Ambulance/Fire', 'number' => '995', 'note' => 'Singapore'],
            ['country_code' => 'AU', 'service' => 'Emergency', 'number' => '000', 'note' => 'Australia'],
            ['country_code' => 'ZA', 'service' => 'Emergency', 'number' => '112', 'note' => 'South Africa mobile'],
            ['country_code' => 'ZA', 'service' => 'Police', 'number' => '10111', 'note' => 'South Africa'],
            ['country_code' => 'MX', 'service' => 'Emergency', 'number' => '911', 'note' => 'Mexico'],
            ['country_code' => 'CA', 'service' => 'Emergency', 'number' => '911', 'note' => 'Canada'],
            ['country_code' => 'IS', 'service' => 'Emergency', 'number' => '112', 'note' => 'Iceland'],
            ['country_code' => 'MA', 'service' => 'Police', 'number' => '190', 'note' => 'Morocco'],
            ['country_code' => 'MA', 'service' => 'Ambulance/Fire', 'number' => '150', 'note' => 'Morocco'],
            ['country_code' => 'AR', 'service' => 'Emergency', 'number' => '911', 'note' => 'Argentina'],
            ['country_code' => 'AR', 'service' => 'Medical', 'number' => '107', 'note' => 'Argentina'],
            ['country_code' => 'KE', 'service' => 'Emergency', 'number' => '999', 'note' => 'Kenya'],
            ['country_code' => 'KE', 'service' => 'Ambulance', 'number' => '1199', 'note' => 'Kenya'],
        ];

        foreach ($emergencyContacts as $contact) {
            EmergencyContact::updateOrCreate(
                [
                    'country_code' => $contact['country_code'],
                    'service' => $contact['service'],
                    'number' => $contact['number'],
                ],
                $contact
            );
        }
    }
}
